### ISSUE TITLE
confusing dimensions in mlpack_sparse_coding help

### ISSUE THREAD

**Issue by kakila** [mlpack/mlpack#1079]
The html help of the CLI [mlpack_sparse_coding](http://www.mlpack.org/docs/mlpack-2.2.4/man/mlpack_sparse_coding.html) has an weird description of the shapes and sizes of the decomposition of the data matrix.
In the current text it seems that a n-by-m matrix is descried as "a matrix with m things and n other-things", so columns/rows are inverted in the plain language description. This is confusing, usually you read first the rows then the columns.

I guess it should read (being consistent with the notation of the mathematical description of the algorithm), [] are optional:

> Given a dense [d-by-n] data matrix X with d dimensions and n points, sparse coding seeks to find a dense [d-by-k] dictionary matrix D with k atoms in d dimensions, and a sparse [k-by-n] coding matrix Z with n points in k dimensions.

**Comment by rcurtin** [comment]
Sure, I agree this is a nice improvement.  I committed this simple change in 031ac93.  Please feel free to send more documentation suggestions in the future; good documentation is really hard to do and the more help we get the better we can make the docs. :)  Thanks!

**Comment by kakila** [comment]
Thanks, the help now is still missing information of what the CSV files should have. Somewhere else in the documentation it si explained that a n-by-d X matrix printed to a CSV file will be read in as a d-by-n. so the help is valid for this transposed matrix, but the user might think they have to actually put that in the CSV, this is not the case.
A line is needed explaining what the  input is and what the outputs are (options -c and -d). Currently the input is the untransposed n-by-d X matrix, but the outputs (dictionary D and codes Z) are transposed, meaning that $DZ$ cannot be calculated, but $ZD$, i.e. to regenerate X one needs to do $D^\topZ^\top$.
The simple fix is to explin this in the documentation. The better but more complicated (also due to back compatibility) is to fix the outputs D and Z to be compatible with the input

**Comment by rcurtin** [comment]
I think the sufficient thing to do here is just to change the documentation to say that `X` can be recovered by calculating `Z * D` not `D * Z`.  I made that change in 6395726.  Thanks for pointing out the issue. :)
