### ISSUE TITLE
Building mlpack through homebrew | Errors

### ISSUE THREAD

**Issue by saketkc** [mlpack/mlpack#403]
I am pretty new to `mlpack` and like everyone else faced a couple of issues getting it up and running.
I find it easier building through [linuxbrew](https://github.com/Homebrew/linuxbrew).

I updated mlpack on `homebrew-science`: https://github.com/Homebrew/homebrew-science/pull/1819

But it seems to be failing on Jenkins. The travis build can be ignored. However even if armadillo is build using `hdf5`, `make tests` reports warnings:

```
[WARN ] Attempted to save HDF5 data to 'test_file.h5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.he5', but Armadillo was compiled without HDF5 support.  Save failed.

```

The Jenkins build failure seems to be due to floating point error, but I do not have a Mac to confirm this.

**Comment by rcurtin** [comment]
These warnings are expected.  The tests check that loading from HDF5 fails when Armadillo is compiled without HDF5 support.  I've committed a fix to disable the `[WARN ]` output.  Thanks for pointing that out.  mlpack does not explicitly require libhdf5; instead, if Armadillo is compiled with HDF5 support (if ARMA_USE_HDF5 is enabled in config.hpp), then mlpack will use the HDF5 functionality.  If Armadillo is not compiled with HDF5 support, then mlpack won't make use of it.  So I'm not sure what the downstream issue is, or if they're just confused by the warnings, but hopefully my changes will help for the next release.  If I can help clarify anything about mlpack in that effort, please let me know.

I don't know what Jenkins build you are referring to.  None of the Jenkins builds are on OS X.  There is an issue with loading and saving that I introduced and need to look into, but have not had time to fix yet.  Also, the Jenkins builds test the current master branch in git, which is significantly different than the 1.0.12 release that you updated for homebrew-science.

Often it is far easier to just install mlpack via your package manager.  It is only for local installs that you have to start worrying about things like `LD_LIBRARY_PATH` and manually selecting include directories (the libxml2 issue aside, which is an open issue that needs to be fixed).  mlpack is packaged for Debian (and derivatives) and Fedora, and I think also Arch and Gentoo and numerous other minor distributions.  Anyway, I think that if you're doing local installs, then it should be reasonable to expect some reasonable familiarity with the intricacies of using shared libraries and linkers.

**Comment by saketkc** [comment]
I should clarified a bit further.

Armadillo is in fact built with hdf5 support, and we still see the warnings.
https://github.com/Homebrew/homebrew-science/pull/1819/files#diff-2e6205c4e12cd1dafdb5284a684acf07R13

Jenkins build results for homebrew-science are built for Mac: http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/997/

**Comment by saketkc** [comment]
Oh and I love the intricacies that come with building stuff from scratch ;-)

**Comment by saketkc** [comment]
And homebrew manages including directories, so that is not an issue at all. I am not aware of the libxml2 issue, but it is handled in there.

See:
http://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/997/version=mavericks/testReport/brew-test-bot/mavericks/install_mlpack/

**Comment by rcurtin** [comment]
Okay, different Jenkins.  Thanks for the link.

Glancing at armadillo.rb, it is almost certainly not being built correctly with HDF5 support.  If you modify config.hpp before running CMake, then CMake will completely overwrite the changes that you made.  Take a look at Armadillo's CMakeLists.txt.  Instead, specify that you want HDF5 manually with the option `-DDETECT_HDF5=ON` and ensure that HDF5 and headers are installed on the system.  Checking the output of CMake to determine if HDF5 was found will ensure that your installation is correct.

The test failures I am seeing are these:

```
/tmp/mlpack-pzGEIF/mlpack-mlpack-1.0.12/src/mlpack/tests/svd_batch_test.cpp:98: fatal error in "SVDBatchMomentumTest": critical check RMSE_2 <= RMSE_1 failed [0.9185867037696458 > 0.91157712642902167]
/tmp/mlpack-pzGEIF/mlpack-mlpack-1.0.12/src/mlpack/tests/svd_batch_test.cpp:149: fatal error in "SVDBatchRegularizationTest": critical check RMSE_2 <= RMSE_1 failed [0.91787583628169389 > 0.91157712642902167]
/tmp/mlpack-pzGEIF/mlpack-mlpack-1.0.12/src/mlpack/tests/svd_incremental_test.cpp:123: fatal error in "SVDIncompleteIncrementalRegularizationTest": critical check RMSE_2 < RMSE_1 failed [0.92918024945339284 >= 0.92886091107661617]
```

Are those the ones you are talking about?  If so, we should open a separate ticket for those, because the issue there may be somewhat complex.  I don't have an OS X system, so I can't reproduce or investigate, unfortunately.  That issue does not appear on any of the numerous Linux systems we have set up with our Jenkins setup.

**Comment by dpo** [comment]
This is how Homebrew builds Armadillo with HDF5 support:
````
cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/armadillo/4.600.2 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DDETECT_HDF5=ON
````
so we do use `-DDETECT_HDF5=ON`. The log suggests that the HDF5 lib is correctly detected:
````
-- HDF5_FOUND = TRUE
-- Set ARMA_HDF5_INCLUDE_DIR to /usr/local/include
...
-- *** ARMA_LIBS = -framework Accelerate;/usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/usr/local/lib/libarpack.dylib
````
The Armadillo dynamic lib also indicates that it is correctly linked against the HDF5 lib:
````
$ otool -L /usr/local/Cellar/armadillo/4.600.2/lib/libarmadillo.dylib
/usr/local/Cellar/armadillo/4.600.2/lib/libarmadillo.dylib:
	/usr/local/lib/libarmadillo.4.dylib (compatibility version 4.0.0, current version 4.60.2)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/local/lib/libhdf5.9.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/local/lib/libsz.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
````

So as far as I can tell, Armadillo is built correctly against HDF5. But every time I build MLPack and run the tests I get
````
[WARN ] Cannot determine type of file 'noextension'; no extension is present.  Load failed.
[WARN ] No extension given with filename 'noextension'; type unknown.  Save failed.
[WARN ] Cannot open file 'nonexistentfile_______________.csv'; load failed.
[WARN ] Loading 'test_file.bin' as raw binary formatted data; but this may not be the actual filetype!
Mat::load(): unsupported file type
Mat::load(): couldn't load from the given stream
[WARN ] Loading from 'test_file.h5' failed.
/tmp/mlpack-iTRtWh/mlpack-mlpack-1.0.12/src/mlpack/tests/load_save_test.cpp:411: fatal error in "LoadHDF5Test": critical check data::Load("test_file.h5", test) == true failed
[WARN ] Save to 'test_file.h5' failed.
/tmp/mlpack-iTRtWh/mlpack-mlpack-1.0.12/src/mlpack/tests/load_save_test.cpp:459: fatal error in "SaveHDF5Test": critical check data::Save("test_file.h5", test) == true failed
````

**Comment by rcurtin** [comment]
> So as far as I can tell, Armadillo is built correctly against HDF5.

I don't think this is correct.  If Armadillo is claiming that it does not have HDF5 support (which it is: `Mat::load(): unsupported file type`), then there must have been some error in the configuration process.  Can you paste or find some way to show me the `armadillo_bits/config.hpp` that results from Homebrew's Armadillo configuration and installation script?

**Comment by dpo** [comment]
I guess you're right. Here's the file you requested: https://gist.github.com/244482e4be0202fe6a82

The HDF5 parts appear to be commented out, which seems contradictory with Armadillo's output.

**Comment by rcurtin** [comment]
Hm, interesting.  Is there any way that you can grab the `config.hpp` file generated during the Armadillo build process and compare it?  It will be in `${ARMADILLO_BUILD_ROOT}/tmp/include/config.hpp`.

The fact that you are getting the message

```
-- Set ARMA_HDF5_INCLUDE_DIR to /usr/local/include
```

implies that `ARMA_USE_HDF5_ALT` should be set in `config.hpp`, but it isn't, which is confusing to me.  Maybe it's accidentally being stripped somewhere?

**Comment by dpo** [comment]
https://gist.github.com/cde063819b00537245af

**Comment by dpo** [comment]
ps: this is with Armadillo 4-600.2. Yesterday I tried 4-650.2, but I get the same messages.

**Comment by rcurtin** [comment]
I'm stumped, and I don't have a good reason why this is happening, and unfortunately I don't have a way to reproduce it either.  Something weird is happening during the configuration step that is causing the line `#define ARMA_USE_HDF5_ALT` to be instead generated as `/* #undef ARMA_USE_HDF5_ALT */`, and I'm not sure what or why it's happening.  As far as I can tell, the Armadillo CMake configuration is okay, and the way you are calling it seems fine too.

One stopgap solution is simply to disable HDF5 support until the issue can be resolved.  I'd help but I have no OS X system to reproduce and investigate on.

**Comment by dpo** [comment]
We enabled HDF5 support because some users needed it in `mlpack`. What is `config.hpp` supposed to look like if HDF5 is correctly detected and enabled?

**Comment by dpo** [comment]
For what it's worth, I just tried compiling `armadillo` by hand (i.e., Homebrew is not involved, except that we hope `armadillo` picks up the HDF5 that was installed via Homebrew). It turns out that `tmp/include/armadillo_bits/config.hpp` has
````
#define ARMA_USE_HDF5_ALT
````
but after I run `make`, things change:
````
$ diff tmp/include/armadillo_bits/config.hpp include/armadillo_bits/config.hpp
27c27
< #define ARMA_USE_ARPACK
---
> // #define ARMA_USE_ARPACK
32c32
< #define ARMA_USE_WRAPPER
---
> // #define ARMA_USE_WRAPPER
56,57c56,57
< /* #undef ARMA_USE_ATLAS */
< #define ARMA_ATLAS_INCLUDE_DIR /
---
> // #define ARMA_USE_ATLAS
> // #define ARMA_ATLAS_INCLUDE_DIR /usr/include/
93c93
< #define ARMA_USE_HDF5_ALT
---
> // #define ARMA_USE_HDF5_ALT
98c98
<   #define ARMA_HDF5_INCLUDE_DIR /usr/local/Cellar/hdf5/1.8.14/include/
---
>   // #define ARMA_HDF5_INCLUDE_DIR /usr/include/
171c171
< /* #undef ARMA_USE_EXTERN_CXX11_RNG */
---
>       // #define ARMA_USE_EXTERN_CXX11_RNG
````
Does that make any sense to you?

**Comment by rcurtin** [comment]
Sorry for the slow response.  The way the Armadillo configuration file should look is that `ARMA_USE_HDF5_ALT` should be set if `DETECT_HDF5` is set when CMake configures the project and HDF5 is found.

Nowthere is another shred of oddity here. Armadillo copies all of its sources temporarily to `tmp/` and modifies that `config.hpp` (`tmp/include/armadillo_bits/config.hpp`)

**Comment by rcurtin** [comment]
Oops, hit 'comment' too early (phones are hard).

When Armadillo then installs, it copies `tmp/` to `/use/include/`. In the links you have given above, it looks like

 * the Gist, which I think is the `tmp/include/armadillo_bits/config.hpp` that the Homebrew configuration has produced, is not configured correctly: HDF5 is not enabled.

 * Your hand compilation is successful: `tmp/include/armadillo_bits/config.hpp` has HDF5 enabled.

But what I don't know is what is different between these two approaches. Can you dig a little deeper and figure out exactly which calls are different?  I'm not convinced that there is an actual bug in the Armadillo configuration scripts here: I think maybe the issue is with how Homebrew is invoking the configuration and install scripts, but I don't have enough clues to know for certain. I'm happy to help with the digging process though... :)
