### ISSUE TITLE
bug in HMM

### ISSUE THREAD

**Issue by warpuv** [mlpack/mlpack#600]
In file mlpack\methods\hmm\hmm_impl.hpp, line 169:
```
    if (dataSeq.size() == 0)
      initial = newInitial / dataSeq.size();
```
Should be probably `dataSeq.size() > 1`.
mlpack version 2.0.1

**Comment by rcurtin** [comment]
There's something deeper that's wrong here, but I need to find my copy of the Elliot, Aggoun, and Moore book to figure out exactly what's up.  So this may take a few days (since I'm out of town).  Thanks for pointing the issue out!

**Comment by rcurtin** [comment]
d6d38a1 should fix the issue.  There was also an issue with how the `newInitial` matrix was being set.  Thanks for reporting the problem!

**Comment by warpuv** [comment]
You forgot to add else condition. initial is not changing if number of sequences equal to one. Thanks for fixing.

**Comment by rcurtin** [comment]
Good catch, thanks for checking my work.  e0e7ba5 should fix this.
